#ifndef _TOKENIZER_H
#define _TOKENIZER_H

typedef enum {
	DATA_STATE,
	CHARACTER_REFERENCE_IN_DATA_STATE,
	RCDATA_STATE,
	CHARACTER_REFERENCE_IN_RCDATA_STATE,
	RAWTEXT_STATE,
	SCRIPT_DATA_STATE,
	PLAINTEXT_STATE,
	TAG_OPEN_STATE,
	END_TAG_OPEN_STATE,
	TAG_NAME_STATE,
	RCDATA_LESS_THAN_SIGN_STATE,
	RCDATA_END_TAG_OPEN_STATE,
	RCDATA_END_TAG_NAME_STATE,
	RAWTEXT_LESS_THAN_SIGN_STATE,
	RAWTEXT_END_TAG_OPEN_STATE,
	RAWTEXT_END_TAG_NAME_STATE,
	SCRIPT_DATA_LESS_THAN_SIGN_STATE,
	SCRIPT_DATA_END_TAG_OPEN_STATE,
	SCRIPT_DATA_END_TAG_NAME_STATE,
	SCRIPT_DATA_ESCAPE_START_STATE,
	SCRIPT_DATA_ESCAPE_START_DASH_STATE,
	SCRIPT_DATA_ESCAPED_STATE,
	SCRIPT_DATA_ESCAPED_DASH_STATE,
	SCRIPT_DATA_ESCAPED_DASH_DASH_STATE,
	SCRIPT_DATA_ESCAPED_LESS_THAN_SIGN_STATE,
	SCRIPT_DATA_ESCAPED_END_TAG_OPEN_STATE,
	SCRIPT_DATA_ESCAPED_END_TAG_NAME_STATE,
	SCRIPT_DATA_DOUBLE_ESCAPE_START_STATE,
	SCRIPT_DATA_DOUBLE_ESCAPED_STATE,
	SCRIPT_DATA_DOUBLE_ESCAPED_DASH_STATE,
	SCRIPT_DATA_DOUBLE_ESCAPED_DASH_DASH_STATE,
	SCRIPT_DATA_DOUBLE_ESCAPED_LESS_THAN_SIGN_STATE,
	SCRIPT_DATA_DOUBLE_ESCAPE_END_STATE,
	BEFORE_ATTRIBUTE_NAME_STATE,
	ATTRIBUTE_NAME_STATE,
	AFTER_ATTRIBUTE_NAME_STATE,
	BEFORE_ATTRIBUTE_VALUE_STATE,
	ATTRIBUTE_VALUE_DOUBLE_QUOTED_STATE,
	ATTRIBUTE_VALUE_SINGLE_QUOTED_STATE,
	ATTRIBUTE_VALUE_UNQUOTED_STATE,
	CHARACTER_REFERENCE_IN_ATTRIBUTE_VALUE_STATE,
	AFTER_ATTRIBUTE_VALUE_QUOTED_STATE,
	SELF_CLOSING_START_TAG_STATE,
	BOGUS_COMMENT_STATE,
	MARKUP_DECLARATION_OPEN_STATE,
	COMMENT_START_STATE,
	COMMENT_START_DASH_STATE,
	COMMENT_STATE,
	COMMENT_END_DASH_STATE,
	COMMENT_END_STATE,
	COMMENT_END_BANG_STATE,
	DOCTYPE_STATE,
	BEFORE_DOCTYPE_NAME_STATE,
	DOCTYPE_NAME_STATE,
	AFTER_DOCTYPE_NAME_STATE,
	AFTER_DOCTYPE_PUBLIC_KEYWORD_STATE,
	BEFORE_DOCTYPE_PUBLIC_IDENTIFIER_STATE,
	DOCTYPE_PUBLIC_IDENTIFIER_DOUBLE_QUOTED_STATE,
	DOCTYPE_PUBLIC_IDENTIFIER_SINGLE_QUOTED_STATE,
	AFTER_DOCTYPE_PUBLIC_IDENTIFIER_STATE,
	BETWEEN_DOCTYPE_PUBLIC_AND_SYSTEM_IDENTIFIERS_STATE,
	AFTER_DOCTYPE_SYSTEM_KEYWORD_STATE,
	BEFORE_DOCTYPE_SYSTEM_IDENTIFIER_STATE,
	DOCTYPE_SYSTEM_IDENTIFIER_DOUBLE_QUOTED_STATE,
	DOCTYPE_SYSTEM_IDENTIFIER_SINGLE_QUOTED_STATE,
	AFTER_DOCTYPE_SYSTEM_IDENTIFIER_STATE,
	BOGUS_DOCTYPE_STATE,
	CDATA_SECTION_STATE
} TokenizerState;

typedef enum {
	CHARACTER_TOKEN,
	CHARACTER_TOKENS,
	TAG_TOKEN,
	EOF_TOKEN
} TokenTypes;

typedef struct {
	TokenizerState state;
	char *input;
	short position;
} Tokenizer;

typedef struct {
	char tagName[16];
	short tagNameLength;
} TagToken;

Tokenizer *NewTokenizer();
void DisposeTokenizer(Tokenizer *tokenizer);

#endif
